version: 1.0.{build}
build:
  verbosity: minimal

install:
  git submodule update --init --recursive

before_build:
  - echo "Building Boost program_optiosn module"
  - cd c:\Libraries\boost_1_59_0
  - bootstrap.bat --with-libraries=program_options
  - b2.exe --with-program_options
  - echo Running cmake...
  - cd c:\projects\bmc
  - cmake -G "Visual Studio 14 2015 Win64" -Dbmc_USE_PYTHON=OFF -DBoost_DEBUG=1 -DBOOST_ROOT=C:\Libraries\boost_1_59_0 -DBOOST_INCLUDEDIR=C:\Libraries\boost_1_59_0 -DBOOST_LIBRARYDIR=C:\Libraries\boost_1_59_0\stage\lib .
  - dir c:\libraries\boost_1_59_0\stage\lib
  - type CMakeCache.txt
  